layer:
  name: "keikakukumeisho"
  zoom:
    min: 2
    max: 9
  dissolve:
    tool: "ogr2ogr"
    output: "processed/merged_keikakukumeisho_dissolved.fgb"
    format: "FlatGeobuf"
    sql: >-
      SELECT ST_Union(geometry) as geometry, 
             計画区名称 
      FROM merged 
      GROUP BY 計画区名称
  tippecanoe:
    options:
      - "--no-tile-size-limit"
      - "--no-feature-limit"
      - "--no-simplification-of-shared-nodes"
      - "--detect-shared-borders"
    attributes:
      - "計画区名称"
