layer:
  name: "kokuyurinmeisho"
  zoom:
    min: 10
    max: 13
  dissolve:
    tool: "ogr2ogr"
    output: "processed/merged_kokuyurinmeisho_dissolved.fgb"
    format: "FlatGeobuf"
    sql: >-
      SELECT ST_Union(geometry) as geometry, 
             国有林名称, 
             計画区名称 
      FROM merged 
      GROUP BY 国有林名称, 計画区名称
  tippecanoe:
    options:
      - "--no-tile-size-limit"
      - "--no-feature-limit"
      - "--no-simplification-of-shared-nodes"
      - "--detect-shared-borders"
    attributes:
      - "国有林名称"
      - "計画区名称"
