dataset:
  name: "kokuyurinya"
  version: "2024.1"
  title: "国土数値情報 国有林野データ 2019年度（令和元年度）版"
  attribution: "<a href='https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A45.html'>国土数値情報 国有林野データ</a>"
  geometry_type: "Polygon"

preprocessing:
  merge:
    tool: "ogrmerge"
    options:
      - "-single"
    output: "processed/merged.geojson"
