name: Generate PMTiles

on:
  push:
    paths:
      - 'data/source/**'
      - 'config/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # GitHub Releasesへの書き込み権限を追加
    steps:
      - uses: actions/checkout@v4

      - name: Setup GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin

      - name: Setup tippecanoe
        run: |
          git clone https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j
          sudo make install

      - name: Create necessary directories
        run: |
          mkdir -p data/processed
          mkdir -p experiments
          mkdir -p production/{latest,archive}

      - name: Merge GeoJSON files
        run: |
          python3 $(which ogrmerge.py) -single \
            -o data/processed/merged.geojson \
            data/source/*.geojson || echo "No source files found"

      - name: Generate detail layer
        run: |
          tippecanoe -o data/processed/detail.mbtiles \
            -z14 -Z14 \
            --no-tile-size-limit --no-feature-limit \
            -l detail \
            data/processed/merged.geojson

      - name: Generate kokuyurinmeisho layer
        run: |
          # ディゾルブ処理
          ogr2ogr -f FlatGeobuf \
            data/processed/merged_kokuyurinmeisho_dissolved.fgb \
            data/processed/merged.geojson \
            -dialect sqlite \
            -sql "SELECT ST_Union(geometry) as geometry, A45_013, A45_024 FROM merged GROUP BY A45_013, A45_024"

          # タイル化
          tippecanoe -o data/processed/kokuyurinmeisho.mbtiles \
            -z13 -Z10 \
            --no-tile-size-limit --no-feature-limit \
            -l kokuyurinmeisho \
            --no-simplification-of-shared-nodes \
            --detect-shared-borders \
            data/processed/merged_kokuyurinmeisho_dissolved.fgb

      - name: Generate keikakukumeisho layer
        run: |
          # ディゾルブ処理
          ogr2ogr -f FlatGeobuf \
            data/processed/merged_keikakukumeisho_dissolved.fgb \
            data/processed/merged.geojson \
            -dialect sqlite \
            -sql "SELECT ST_Union(geometry) as geometry, A45_024 FROM merged GROUP BY A45_024"

          # タイル化
          tippecanoe -o data/processed/keikakukumeisho.mbtiles \
            -z9 -Z2 \
            --no-tile-size-limit --no-feature-limit \
            -l keikakukumeisho \
            --no-simplification-of-shared-nodes \
            --detect-shared-borders \
            data/processed/merged_keikakukumeisho_dissolved.fgb

      - name: Join tiles
        run: |
          tile-join -o production/latest/kokuyurinya.pmtiles \
            -n "国土数値情報 国有林野データ 2019年度（令和元年度）版" \
            -A "<a href='https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A45.html'>国土数値情報 国有林野データ</a>" \
            --overzoom \
            --no-tile-size-limit \
            data/processed/detail.mbtiles \
            data/processed/kokuyurinmeisho.mbtiles \
            data/processed/keikakukumeisho.mbtiles

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.DATE }}
          tag_name: v${{ env.DATE }}
          files: |
            production/latest/kokuyurinya.pmtiles
          body: |
            PMTiles generated on ${{ env.DATE }}
            
            ## Changes
            - Update from source data
            
            ## Download
            Direct link to PMTiles: ${{ github.server_url }}/${{ github.repository }}/releases/download/v${{ env.DATE }}/kokuyurinya.pmtiles

      - name: Update README with latest PMTiles URL
        run: |
          cat > README.md << EOF
          # Polygon PMTiles Generator
          
          最新のPMTilesファイル:
          ${{ github.server_url }}/${{ github.repository }}/releases/latest/download/kokuyurinya.pmtiles
          
          ## 更新履歴
          - ${{ env.DATE }}: データ更新
          EOF
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update PMTiles URL" || echo "No changes to commit"
          git push || echo "No changes to push"